---

- name: Provision cluster
  hosts: localhost
  gather_facts: False
  vars:
    # The following vars should probably be overridden
    - name: ETL
    - instance_groups:
        master:
          num_instances: 1
          type: m1.medium
          market: ON_DEMAND
        core:
          num_instances: 2
          type: m1.medium
          market: ON_DEMAND
        task:
          num_instances: 1
          type: m1.medium
          market: SPOT
          bidprice: 0.03
    - task_instance_bid: 0.03
    - bootstrap_actions: {}
    - steps: {}
    # The following vars may be overridden
    - keypair_name: "{{ lookup('env', 'AWS_KEYPAIR_NAME') }}"
    - role: emr
    - ami_version: 2.4.7
    # The following variables *must* be overridden
    # - vpc_subnet_id: subnet-7bc4913d
    # - user_info: []
    # - log_uri: s3://some-bucket-name
  tasks:
    - name: provision EMR cluster
      local_action:
        module: emr
        name: "{{ name }}"
        keypair_name: "{{ keypair_name }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        log_uri: "{{ log_uri }}"
        visible_to_all_users: yes
        job_flow_role: "{{ role }}"
        ami_version: "{{ ami_version }}"
        instance_groups: $instance_groups
        bootstrap_actions: $bootstrap_actions
        steps: $steps
      register: jobflow

    - name: add master to group
      local_action: >
        add_host hostname={{ jobflow.master_private_ip }} groupname=launched_master ansible_ssh_user=hadoop ansible_connection=ssh

    - name: display master IP address
      debug: msg={{ jobflow.master_private_ip }}

    - name: display job flow ID
      debug: msg={{ jobflow.jobflow_id }}


- name: Configure SSH access to cluster
  hosts: launched_master
  gather_facts: False
  sudo: True
  roles:
    - user
